version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: luckydoki
      MYSQL_USER: luckydoki
      MYSQL_PASSWORD: luckydoki
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci