#version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: luckydoki
      MYSQL_USER: luckydoki
      MYSQL_PASSWORD: luckydoki
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
    volumes:
      - /Users/rjy/docker/mysql/conf.d:/etc/mysql/conf.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci



    # MongoDB 설정  추가
  mongodb:
    image: mongo:latest
    container_name: chatdb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: luckydoki
      MONGO_INITDB_ROOT_PASSWORD: luckydoki
      MONGO_INITDB_DATABASE: chatdb
    volumes:
      - mongodb_data:/data/db
      # 초기화 스크립트가 필요한 경우 주석 해제
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

networks:
  app-network:
#       driver: bridge
#
volumes:
  mongodb_data:


